<a href="https://colab.research.google.com/github/tzelleke/jupyter-notebooks/blob/master/pandas/string-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nb2hugo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nb2hugo
  Downloading nb2hugo-0.1.4-py3-none-any.whl (8.8 kB)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/dist-packages (from nb2hugo) (5.1.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.7/dist-packages (from nb2hugo) (5.4.0)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from nb2hugo) (3.6.4)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from nb2hugo) (5.6.1)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (0.6.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (2.6.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (0.4)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (5.0.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (4.11.1)
Requirement already satisfied: jinja2>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbconvert->nb2hugo) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.4->nbconvert->nb2hugo) (2.0.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.7/dist-packages (from nbformat->nb2hugo) (4.3.3)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.7/dist-packages (from nbformat->nb2hugo) (2.16.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat->nb2hugo) (4.1.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat->nb2hugo) (5.9.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat->nb2hugo) (0.18.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat->nb2hugo) (4.12.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat->nb2hugo) (22.1.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema>=2.6->nbformat->nb2hugo) (3.8.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->nb2hugo) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->nb2hugo) (0.5.1)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->nb2hugo) (1.4.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->nb2hugo) (57.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->nb2hugo) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->nb2hugo) (8.14.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->nb2hugo) (1.11.0)
Installing collected packages: argparse, nb2hugo
Successfully installed argparse-1.4.0 nb2hugo-0.1.4

In [ ]:
import io
import pandas as pd

## Phone numbers - simple

Let us create some sample data.

In [ ]:
csv = io.StringIO('\n'.join([
    'ID,Name,Phones',
    '1,Russel,"01234567\n02345678\n03456789"',
    '2,Patrick,"04123456\n05234567\n06345678"',
]))

df = pd.read_csv(csv, index_col='ID')
df

       Name                        Phones
ID
1    Russel  01234567\n02345678\n03456789
2   Patrick  04123456\n05234567\n06345678

The `Phones` column in this dataframe contains multiple phone numbers separated by line breaks for each record.
We are going to reshape the dataframe to hold

In [ ]:
df.assign(
    Phones=df.Phones.str.split('\n')
).explode('Phones')

       Name    Phones
ID
1    Russel  01234567
1    Russel  02345678
1    Russel  03456789
2   Patrick  04123456
2   Patrick  05234567
2   Patrick  06345678

Note, that the index `ID` is no longer unique.
`DataFrame.assign` is used to add new columns to a dataframe.

## Phone numbers with phone type

Next, we are going to look at a more complicated case where

In [ ]:
csv = io.StringIO('\n'.join([
    'ID,Name,Phones',
    '1,Russel,"mobil: 01234567\nwork: 02345678\nprivate: 03456789"',
    '2,Patrick,"mobil: 04123456\nprivate: 05234567"',
]))

df = pd.read_csv(csv, index_col='ID')
df

       Name                                             Phones
ID
1    Russel  mobil: 01234567\nwork: 02345678\nprivate: 0345...
2   Patrick                 mobil: 04123456\nprivate: 05234567

dfdsfadsgfasdfa

In [ ]:
df.join(
    df.Phones
        .str.split('\n').explode()
        .str.split(':', expand=True)
        .rename(columns={
            0: 'phone_type',
            1: 'phone_number',
        })
).drop('Phones', axis='columns')

       Name phone_type phone_number
ID
1    Russel      mobil     01234567
1    Russel       work     02345678
1    Russel    private     03456789
2   Patrick      mobil     04123456
2   Patrick    private     05234567

### Reshaping to wide format

We can reshape this dataframe to a wide format by using the idiom  
`DataFrame.set_index('<COLUMN>', append=True).unstack('<COLUMN>')`.  
[set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) sets the DataFrame index using existing columns.
If we specify `append=True` the column is added to the existing index instead of replacing it. Thus, after this operation the dataframe has a MultiIndex.

In [ ]:
(
    df.Phones
        .str.split('\n').explode()
        .str.split(':', expand=True)
        .rename(columns={
            0: 'phone_type',
            1: 'phone_number',
        })
        .set_index('phone_type', append=True)
        .unstack('phone_type').droplevel(0, axis='columns')
)

phone_type      mobil    private       work
ID
1            01234567   03456789   02345678
2            04123456   05234567        NaN

gfafgasdgfasdf

In [ ]:
df.join(
    df.Phones
        .str.split('\n').explode()
        .str.split(':', expand=True)
        .rename(columns={
            0: 'phone_type',
            1: 'phone_number',
        })
        .set_index(['phone_type'], append=True)
        .unstack('phone_type').droplevel(0, axis='columns')
).drop('Phones', axis='columns')

       Name      mobil    private       work
ID
1    Russel   01234567   03456789   02345678
2   Patrick   04123456   05234567        NaN

In [ ]:
import re

from traitlets import List
from nbconvert.preprocessors import Preprocessor
from nb2hugo.exporter import HugoExporter
from nb2hugo.writer import HugoWriter

In [ ]:
class TableExtractor(Preprocessor):
    pattern_table = re.compile(r'(?s:<table\b.*</table>\n)')
    pattern_table_border = re.compile(r'(?<=<table\b)(\sborder=\S+)')
    pattern_table_style = re.compile(r'(?<=\w\b)(\sstyle=[^>]+)')

    def preprocess_cell(self, cell, resources, index):
        if cell.cell_type == 'code' and len(cell.outputs):
            html = cell.outputs[0]['data']['text/html']
            html = TableExtractor.pattern_table.search(html).group(0)
            html = TableExtractor.pattern_table_border.sub('', html)
            html = TableExtractor.pattern_table_style.sub('', html)
            cell.outputs[0]['data']['text/html'] = html
        return cell, resources

In [ ]:
class Exporter(HugoExporter):
    preprocessors = List([TableExtractor]).tag(config=True)

In [ ]:
class Writer(HugoWriter):
    def __init__(self):
        self._exporter = Exporter()

In [ ]:
w = Writer()
w.convert('pandas.ipynb', '.', 'demo')

FileNotFoundError: ignored